pipeline {
    agent any

    environment {
        AWS_REGION = 'ap-south-1'
        PROD_HOST = '13.235.9.106'
        ECR_REPO = '507096509706.dkr.ecr.ap-south-1.amazonaws.com/nodejs-app'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Verify Environment') {
            steps {
                sh '''
                    echo "===== USER ====="
                    whoami

                    echo "===== DOCKER ====="
                    docker --version

                    echo "===== AWS CLI ====="
                    aws --version

                    echo "===== IAM ROLE ====="
                    aws sts get-caller-identity
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('nodejs-app') {
                    sh '''
                        docker build -t nodejs-app:latest .
                    '''
                }
            }
        }

        stage('Login to ECR') {
            steps {
                sh '''
                    aws ecr get-login-password --region $AWS_REGION | \
                    docker login \
                    --username AWS \
                    --password-stdin \
                    $ECR_REPO
                '''
            }
        }

        stage('Tag Image') {
            steps {
                sh '''
                    docker tag nodejs-app:latest $ECR_REPO:latest
                '''
            }
        }

        stage('Push Image') {
            steps {
                sh '''
                    docker push $ECR_REPO:latest
                '''
            }
        }

        stage('Deploy to Production') {
            steps {
                sshagent(credentials: ['prod-ssh-key']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no ubuntu@$PROD_HOST << 'EOF'

                        aws ecr get-login-password --region ap-south-1 | \
                        docker login \
                            --username AWS \
                            --password-stdin \
                            507096509706.dkr.ecr.ap-south-1.amazonaws.com

                        docker pull 507096509706.dkr.ecr.ap-south-1.amazonaws.com/nodejs-app:latest

                        docker images

                        docker stop nodejs-app || true
                        docker rm nodejs-app || true

                        docker run -d \
                        --name nodejs-app \
                        --restart unless-stopped \
                        -p 80:3000 \
                        507096509706.dkr.ecr.ap-south-1.amazonaws.com/nodejs-app:latest

                        sleep 5

                        docker ps

                        curl -f http://localhost/health
                        EOF
                    '''
                }
            }
        }

        stage('Cleanup') {
            steps {
                sh '''
                    docker image prune -f
                '''
            }
        }
    }
}